backend:
  name: github
  repo: UnblockedGames660/UnblockedGames660.github.io  # Your GitHub repo
  branch: main  # Change if using a different branch
  base_url: https://github.com  # GitHub OAuth

media_folder: "assets/uploads" # Where uploaded images/files will be stored
public_folder: "/assets/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: "/"  # Root directory (for index.html & games.html)
    create: false  # Prevent new pages from being created here
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "games"
    label: "Game Pages"
    folder: "/Games"  # Manages game HTML files in /Games
    create: true  # Allows adding new game pages
    slug: "{{slug}}"
    fields:
      - {label: "Game Title", name: "title", widget: "string"}
      - {label: "Game Description", name: "description", widget: "text"}
      - {label: "Embed Code", name: "embed_code", widget: "code", default_language: "html"}
