backend:
  name: github
  repo: UnblockedGames660/UnblockedGames660.github.io  # Your GitHub repo
  branch: main  # The branch to deploy from

media_folder: "assets/uploads"  # Folder to store media files
public_folder: "/assets/uploads"  # Public URL for media

collections:
  - name: "pages"
    label: "Pages"
    folder: "/"  # Root folder for files like index.html, games.html
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "games"
    label: "Games"
    folder: "/Games"  # Folder for metadata or game-related info in /Games
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Game File", name: "game_file", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}

  - name: "game_files"
    label: "Game Files"
    folder: "/Games/src"  # Folder for your actual game files in /Games/src
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Game File", name: "game_file", widget: "string"}  # Specify the HTML file (e.g., eaglercraftx.html)
      - {label: "File Path", name: "file_path", widget: "string"}  # Optional: Specify the file path relative to /Games/src
